package formats

//Request Op Codes
const (
	CreateWindow uint8 = iota + 1
	ChangeWindowAttributes
	GetWindowAttributes
	DestroyWindow
	DestroySubwindows
	ChangeSaveSet
	ReparentWindow
	MapWindow
	MapSubwindows
	UnmapWindow
	UnmapSubwindows
	ConfigureWindow
	CirculateWindow
	GetGeometry
	QueryTree
	InternAtom
	GetAtomName
	ChangeProperty
	DeleteProperty
	GetProperty
	ListProperties
	SetSelectionOwner
	GetSelectionOwner
	ConvertSelection
	SendEvent
	GrabPointer
	UngrabPointer
	GrabButton
	UngrabButton
	ChangeActivePointerGrab
	GrabKeyboard
	UngrabKeyboard
	GrabKey
	UngrabKey
	AllowEvents
	GrabServer
	UngrabServer
	QueryPointer
	GetMotionEvents
	TranslateCoordinates
	WarpPointer
	SetInputFocus
	GetInputFocus
	QueryKeymap
	OpenFont
	CloseFont
	QueryFont
	QueryTextExtents
	ListFonts
	ListFontsWithInfo
	SetFontPath
	GetFontPath
	CreatePixmap
	FreePixmap
	CreateGC
	ChangeGC
	CopyGC
	SetDashes
	SetClipRectangles
	FreeGC
	ClearArea
	CopyArea
	CopyPlane
	PolyPoint
	PolyLine
	PolySegment
	PolyRectangle
	PolyArc
	FillPoly
	PolyFillRectangle
	PolyFillArc
	PutImage
	GetImage
	PolyText8
	PolyText16
	ImageText8
	ImageText16
	CreateColormap
	CopyColormapAndFree
	InstallColormap
	UninstallColormap
	ListInstalledColormaps
	AllocColor
	AllocNamedColor
	AllocColorCells
	AllocColorPlanes
	FreeColors
	StoreColors
	StoreNamedColor
	QueryColors
	LookupColor
	CreateCursor
	CreateGlyphCursor
	FreeCursor
	RecolorCursor
	QueryBestSize
	QueryExtension
	ListExtension
	ChangeKeyboardMapping
	GetKeyboardMapping
	ChangeKeyboardControl
	GetKeyboardControl
	Bell
	ChangePointerControl
	GetPointerControl
	SetScreenSaver
	GetScreenSaver
	ChangeHosts
	ListHosts
	SetAccessControl
	SetCloseDownMode
	KillClient
	RotateProperties
	ForceScreenSaver
	SetPointerMapping
	GetPointerMapping
	SetModifierMapping
	GetModifierMapping
	NoOperation
)

//Request is the format for sending requests
type Request struct {
	OpCode uint8
	Length uint16
	Data   uint8
}
